fieldLayouts:
  9b638048-a78d-4077-acdc-0a19568835d2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: cb849588-0c08-4e4d-9389-6ae4e4fd0613 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: kind
name: kind
siteSettings:
  af4633aa-a171-4f4d-bd70-f6acd0d478c5: # WETO
    hasUrls: true
    template: null
    uriFormat: 'type/{slug}'
structure:
  maxLevels: null
  uid: a3b34156-e63e-4cec-b4d5-311e1142900a
